### ISSUE TITLE
Suggested increase in instruction limit

### ISSUE THREAD

**Issue by WangWenBin2017** [Element-0/Translation#7]
Hello there,
Is there a way to restrict the use of certain instructions? For example, the / warp instruction can also be used in non-op under my test. Can I add a plugin similar to the permission group to restrict the player's instruction operation?

Google translation, grammatical errors and improper wording please forgive me :)

**Comment by HongyiMC** [comment]
This is the translation team for ElementZero
Please go to the actual ElementZero to comment a issue.
